"""Tests for turning registered bloks into agent inputs."""

from dataclasses import dataclass
from typing import Protocol

import pytest

from rekuest_next.app import AppRegistry
from rekuest_next.declare import declare, declare_state
from rekuest_next.state.decorator import state


@declare_state
class RunState:
    """State declared by the protocol the blok depends on."""

    available_protocols: list[str]


@declare(app="opentrons")
class OpentronsLike(Protocol):
    """A remote app the blok drives."""

    RunState: RunState

    def run_protocol(self, protocol: str) -> None:
        """Run a protocol.

        Args:
            protocol (str): The protocol to run.
        """
        ...


@pytest.fixture
def registry() -> AppRegistry:
    return AppRegistry()


# --- demo_state synthesis -------------------------------------------------


def test_demo_state_is_synthesized_for_a_state_with_required_fields(
    registry: AppRegistry,
) -> None:
    @state(registry=registry)
    @dataclass
    class ProtocolState:
        available_protocols: list[str]  # required: no default to construct from
        running_protocol: str | None = None

    registry.register_blok(
        "local", '<Text text="@self.ProtocolState.available_protocols" />'
    )

    blok = registry.get_declared_bloks()["local"]

    assert blok.demo_state == {
        "self": {
            "ProtocolState": {"available_protocols": [], "running_protocol": None},
        }
    }


def test_explicit_demo_state_is_left_alone(registry: AppRegistry) -> None:
    @state(registry=registry)
    @dataclass
    class ProtocolState:
        available_protocols: list[str]

    registry.register_blok(
        "local",
        '<Text text="@self.ProtocolState.available_protocols" />',
        demo_state={"self": {"ProtocolState": {"available_protocols": ["a"]}}},
    )

    blok = registry.get_declared_bloks()["local"]
    assert blok.demo_state["self"]["ProtocolState"]["available_protocols"] == ["a"]


# --- explicit (cross-app) dependencies ------------------------------------


CROSS_APP_BLOK = """
<foreach items="@opentrons.RunState.available_protocols" let="#protocol">
    <Button label="@protocol" onClick="@opentrons.run_protocol(protocol)" />
</foreach>
"""


def test_cross_app_blok_requires_explicit_dependencies(registry: AppRegistry) -> None:
    registry.register_blok("remote", CROSS_APP_BLOK)

    with pytest.raises(ValueError, match="Blok references unknown action"):
        registry.get_declared_bloks()


def test_explicit_dependency_is_used_verbatim(registry: AppRegistry) -> None:
    registry.register_blok(
        "remote",
        CROSS_APP_BLOK,
        dependencies=[OpentronsLike.to_dependency("opentrons")],
    )

    blok = registry.get_declared_bloks()["remote"]
    dependency = blok.dependencies[0]

    assert dependency.key == "opentrons"
    assert dependency.app == "opentrons"
    assert [demand.key for demand in dependency.action_dependencies] == ["run_protocol"]
    assert [demand.key for demand in dependency.state_dependencies] == ["RunState"]


def test_remote_state_is_omitted_from_autogenerated_demo_state(
    registry: AppRegistry,
) -> None:
    # The state has no local definition to synthesize from, and a partial entry
    # would fail the demo_state completeness check.
    registry.register_blok(
        "remote",
        CROSS_APP_BLOK,
        dependencies=[OpentronsLike.to_dependency("opentrons")],
    )

    assert registry.get_declared_bloks()["remote"].demo_state == {}


def test_unknown_action_on_an_explicit_dependency_is_rejected(
    registry: AppRegistry,
) -> None:
    registry.register_blok(
        "remote",
        '<Button onClick="@opentrons.run_protokol(1)" />',
        dependencies=[OpentronsLike.to_dependency("opentrons")],
    )

    with pytest.raises(ValueError, match="Unknown action 'run_protokol'"):
        registry.get_declared_bloks()


# --- operation naming -----------------------------------------------------


def test_dotted_operation_resolves_to_its_last_segment(registry: AppRegistry) -> None:
    # AppRegistry.implementations is keyed by bare interface, so "ns.run_protocol"
    # names the action "run_protocol". Inference and validation must agree.
    registry.register_blok(
        "remote",
        '<Button onClick="@opentrons.ns.run_protocol(1)" />',
        dependencies=[OpentronsLike.to_dependency("opentrons")],
    )

    blok = registry.get_declared_bloks()["remote"]
    assert [demand.key for demand in blok.dependencies[0].action_dependencies] == [
        "run_protocol"
    ]


def test_dotted_operation_with_unknown_last_segment_is_rejected(
    registry: AppRegistry,
) -> None:
    registry.register_blok(
        "remote",
        '<Button onClick="@opentrons.ns.nope(1)" />',
        dependencies=[OpentronsLike.to_dependency("opentrons")],
    )

    with pytest.raises(ValueError, match="Unknown action 'nope'"):
        registry.get_declared_bloks()


def test_state_missing_from_an_explicit_dependency_is_rejected(
    registry: AppRegistry,
) -> None:
    # The mirror of the unknown-action check: an explicit dependency is used
    # verbatim, so a state it does not declare must still fail.
    registry.register_blok(
        "remote",
        '<Text text="@opentrons.NopeState.value" />',
        dependencies=[OpentronsLike.to_dependency("opentrons")],
    )

    with pytest.raises(ValueError, match="state 'NopeState' does not exist"):
        registry.get_declared_bloks()
